version: '2'
services:
    zookeeper:
      image: bwv988/zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"

    postgres:
      image: bwv988/postgres-hive
      container_name: postgres
      ports:
        - "5432:5432"

    namenode:
      image: bwv988/hadoop-namenode
      container_name: namenode
      volumes:
        - ~/ds-playground/hadoop/namenode:/hadoop/dfs/name
        - ~/ds-playground/workdir:/workdir
      environment:
        - CLUSTER_NAME=test
      env_file:
        - env/hadoop.env
      ports:
        - "50070:50070"
        - "8020:8020"

    datanode1:
      image: bwv988/hadoop-datanode
      container_name: datanode1
      depends_on:
          - namenode
      volumes:
        - ~/ds-playground/hadoop/datanode1:/hadoop/dfs/data
      env_file:
        - env/hadoop.env

    hive:
      image: bwv988/hadoop-hive
      depends_on:
        - zookeeper
        - postgres
        - namenode
        - datanode1
      container_name: hive
      env_file:
        - env/hadoop.env
      ports:
        - "10000:10000"
        - "10002:10002"
      volumes:
        - /opt/hive/lib
        - /usr/share/java

    spark-master:
      image: bwv988/ds-spark-master
      container_name: spark-master
      environment:
        - SPARK_CONF_spark_eventLog_enabled=true
        - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
        - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
      env_file:
        - env/hadoop.env
      ports:
        - "8080:8080"
      depends_on:
        - hive
      volumes:
        - ~/ds-playground/workdir/:/workdir
      volumes_from:
        - hive

    spark-worker:
      image: bwv988/ds-spark-worker
      depends_on:
          - spark-master
      environment:
        - SPARK_CONF_spark_eventLog_enabled=true
        - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
        - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
        - SPARK_MASTER_URL=spark://spark-master:7077
      env_file:
        - env/hadoop.env
      volumes_from:
        - spark-master

volumes:
    spark-master:
    hive:
